electricity_source_order = [
    "Electricity|Total",
    "Electricity|Imports",
    "Electricity|Solar",
    "Electricity|Wind",
    "Electricity|Geothermal",
    "Electricity|Hydrogen",
    "Electricity|Gas",
    "Electricity|Nuclear",
    "Electricity|Hydro Dams",
    "Electricity|Hydro RoR",
    "Electricity|Wood",
    "Electricity|Biogas",
    "Electricity|Waste",
]
