name: Deploy to Google Cloud
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        # Either user Workload Identity Federation or Service Account Keys. See
        # above more more examples
        workload_identity_provider: 'projects/926214663254/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-actions@energy-explorer.iam.gserviceaccount.com'

    # This example uses the docker login action
    - uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io' # or REGION-docker.pkg.dev
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    # This example runs "docker login" directly to Container Registry.
    - name: Build and push container
      run: |-
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
        docker build -t gcr.io/energy-explorer/energy_explorer/api:latest api
        docker push gcr.io/energy-explorer/energy_explorer/api:latest

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: energy-explorer-api
        region: europe-west6
        image: gcr.io/energy-explorer/energy_explorer/api:latest


